before_script:
  - docker info

# https://docs.gitlab.com/ee/user/packages/container_registry/index.html#build-and-push-by-using-gitlab-cicd
build-image-latest:
  image: docker:20.10.16
  stage: build
  services:
  - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

deploy_development:
  stage: deploy
  when: manual
  variables:
    DEVELOPMENT_SERVER: $DEVELOPMENT_SERVER
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    #    - chmod 644 ~/.ssh/known_hosts
    - ssh-keyscan ${DEVELOPMENT_SERVER} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploy to development server"
    - ssh ${SSH_USER}@${DEVELOPMENT_SERVER} 'cd /opt/chipa && docker compose pull frontend && docker compose stop frontend && docker compose rm -f frontend && docker compose up frontend -d'
  environment:
    name: development
    url: https://chipa.archertech.ru